#!/usr/bin/env node
import fs from "fs";
import path from "path";
import { fileURLToPath } from "url";

const root = path.resolve(path.dirname(fileURLToPath(import.meta.url)), "..");
const dir = path.join(root, "games", "snakes");
const out = path.join(root, "mobile", "src", "runtime", "snakesBundle.ts");

const css = fs.readFileSync(path.join(dir, "style.css"), "utf8");
const js = fs.readFileSync(path.join(dir, "game.js"), "utf8");

const html = `<!DOCTYPE html>
<html lang="en">
<head>
  <meta charset="utf-8" />
  <meta name="viewport" content="width=device-width, initial-scale=1, maximum-scale=1, user-scalable=no" />
  <title>Snakes &amp; Ladders · Free Play</title>
  <style>${css}</style>
</head>
<body>
  <div class="wrap">
    <div class="meta" id="status">Free Play · you are Purple · roll to start</div>
    <canvas id="board" width="400" height="400"></canvas>
    <div class="row">
      <canvas id="dice" width="56" height="56"></canvas>
      <button type="button" id="rollBtn">Roll</button>
      <button type="button" id="closeBtn" class="ghost">Close</button>
    </div>
    <div class="hint">Snakes slide down · ladders climb up · exact 100 to win. Green is the bot.</div>
  </div>
  <script>${js}</script>
</body>
</html>`;

fs.writeFileSync(out, `/** Auto-generated by scripts/pack-snakes.mjs — do not edit by hand. */\nexport const SNAKES_HTML = ${JSON.stringify(html)};\n`);
console.log("Wrote", out, "(" + Math.round(Buffer.byteLength(html) / 1024) + " KB html)");
