#!/usr/bin/env node
/** Pack games/ludo into a single HTML string for Expo WebView. */
import fs from "fs";
import path from "path";
import { fileURLToPath } from "url";

const root = path.resolve(path.dirname(fileURLToPath(import.meta.url)), "..");
const ludo = path.join(root, "games", "ludo");
const out = path.join(root, "mobile", "src", "runtime", "ludoBundle.ts");

const css = fs.readFileSync(path.join(ludo, "style.css"), "utf8");
const js = fs.readFileSync(path.join(ludo, "game.js"), "utf8");
let body = fs.readFileSync(path.join(ludo, "index.html"), "utf8");
body = body.replace(/<link[^>]*>/g, "");
body = body.replace(/<script[^>]*src=[^>]*><\/script>/g, "");
const inner = body.match(/<body>([\s\S]*)<\/body>/)[1];

const html = `<!DOCTYPE html>
<html lang="en">
<head>
  <meta charset="utf-8" />
  <meta name="viewport" content="width=device-width, initial-scale=1, maximum-scale=1, user-scalable=no" />
  <title>Ludo · Free Play</title>
  <style>${css}</style>
</head>
<body>
${inner}
  <script>${js}</script>
</body>
</html>`;

fs.mkdirSync(path.dirname(out), { recursive: true });
fs.writeFileSync(
  out,
  `/** Auto-generated by scripts/pack-ludo.mjs — do not edit by hand. */\nexport const LUDO_HTML = ${JSON.stringify(html)};\n`
);
console.log("Wrote", out, "(" + Math.round(Buffer.byteLength(html) / 1024) + " KB html)");
