#!/usr/bin/env node
/** Pack games/ludo into a single HTML string for Expo WebView. */
import fs from "fs";
import path from "path";
import { fileURLToPath } from "url";

const root = path.resolve(path.dirname(fileURLToPath(import.meta.url)), "..");
const ludo = path.join(root, "games", "ludo");
const out = path.join(root, "mobile", "src", "runtime", "ludoBundle.ts");

const css = fs.readFileSync(path.join(ludo, "style.css"), "utf8");
const js = fs.readFileSync(path.join(ludo, "game.js"), "utf8");
const html = `<!DOCTYPE html>
<html lang="en">
<head>
  <meta charset="utf-8" />
  <meta name="viewport" content="width=device-width, initial-scale=1, maximum-scale=1, user-scalable=no" />
  <title>Ludo · Free Play</title>
  <style>${css}</style>
</head>
<body>
  <div class="wrap">
    <h1>Ludo</h1>
    <div class="meta" id="status">Free Play · you are Red · roll to start</div>
    <canvas id="board-canvas" width="375" height="375"></canvas>
    <div class="row">
      <canvas id="dice-canvas" width="56" height="56"></canvas>
      <button type="button" id="rollBtn">Roll</button>
      <button type="button" id="closeBtn" class="ghost">Close</button>
    </div>
    <div class="hint">Tap a highlighted piece to move. Six to leave yard. Exact finish.</div>
  </div>
  <script>${js}</script>
</body>
</html>`;

const ts = `/** Auto-generated by scripts/pack-ludo.mjs — do not edit by hand. */
export const LUDO_HTML = ${JSON.stringify(html)};
`;
fs.mkdirSync(path.dirname(out), { recursive: true });
fs.writeFileSync(out, ts);
console.log("Wrote", out, "(" + Math.round(ts.length / 1024) + " KB)");
