#!/usr/bin/env node
import fs from "fs";
import path from "path";
import { fileURLToPath } from "url";

const root = path.resolve(path.dirname(fileURLToPath(import.meta.url)), "..");
const dir = path.join(root, "games", "chess");
const out = path.join(root, "mobile", "src", "runtime", "chessBundle.ts");

const css = fs.readFileSync(path.join(dir, "style.css"), "utf8");
const engine = fs.readFileSync(path.join(dir, "vendor", "chess.min.js"), "utf8");
const js = fs.readFileSync(path.join(dir, "game.js"), "utf8");

const html = `<!DOCTYPE html>
<html lang="en">
<head>
  <meta charset="utf-8" />
  <meta name="viewport" content="width=device-width, initial-scale=1, maximum-scale=1, user-scalable=no" />
  <title>Chess · Free Play</title>
  <style>${css}</style>
</head>
<body>
  <div class="wrap">
    <div class="meta" id="status">Your turn (White)</div>
    <canvas id="board" width="360" height="360"></canvas>
    <div class="row">
      <button type="button" id="newBtn" class="ghost">New game</button>
      <button type="button" id="closeBtn" class="ghost">Close</button>
    </div>
    <div class="hint">Tap a piece, then a square. Black plays random legal moves.</div>
  </div>
  <script>${engine}</script>
  <script>${js}</script>
</body>
</html>`;

fs.writeFileSync(out, `/** Auto-generated by scripts/pack-chess.mjs — do not edit by hand. */\nexport const CHESS_HTML = ${JSON.stringify(html)};\n`);
console.log("Wrote", out, "(" + Math.round(Buffer.byteLength(html) / 1024) + " KB html)");
